# Loading Datasets

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

print("Connecting to MySQL Database...")
db_url = "mysql+pymysql://root:Me_chinmai%4004@localhost:3306/banking_fraud_analytics"
engine = create_engine(db_url)

print("Extracting all raw datasets...")
customers = pd.read_sql("SELECT * FROM Customers", con=engine)
accounts = pd.read_sql("SELECT * FROM Accounts", con=engine)
merchants = pd.read_sql("SELECT * FROM Merchants", con=engine)
transactions = pd.read_sql("SELECT * FROM Transactions", con=engine)
credit_cards = pd.read_sql("SELECT * FROM Credit_Cards", con=engine)
branches = pd.read_sql("SELECT * FROM Branches", con=engine)
device_logins = pd.read_sql("SELECT * FROM Device_Logins", con=engine)
atm_logs = pd.read_sql("SELECT * FROM ATM_Logs", con=engine)
chargebacks = pd.read_sql("SELECT * FROM Chargebacks", con=engine)
fraud_alerts = pd.read_sql("SELECT * FROM Fraud_Alerts", con=engine)

print("Database loaded successfully!\n")

Connecting to MySQL Database...
Extracting all raw datasets...
Database loaded successfully!

# Cleaning Customers Table

In [2]:
clean_customers = customers.copy()
clean_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25134 entries, 0 to 25133
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     25134 non-null  int64
 1   customer_name   25134 non-null  object
 2   gender          25134 non-null  object
 3   age             25134 non-null  int64
 4   city            25134 non-null  object
 5   state           25134 non-null  object
 6   occupation      25134 non-null  object
 7   annual_income   24382 non-null  float64
 8   kyc_status      25134 non-null  object
 9   customer_since  25134 non-null  object
 10  risk_category   24411 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 2.1+ MB

In [3]:
clean_customers.describe()

         customer_id           age  annual_income
count   25134.000000  25134.000000   2.438200e+04
mean   114630.581921     49.189942   9.490705e+05
std     29977.302865     18.661684   8.518480e+05
min    100001.000000     12.000000   6.300000e+01
25%    106284.250000     33.000000   2.358112e+05
50%    112567.500000     49.000000   7.110630e+05
75%    118850.750000     65.000000   1.367587e+06
max    524949.000000    105.000000   3.499778e+06

In [4]:
clean_customers.head(10)

,customer_id,customer_name,gender,age,city,state,occupation,annual_income,kyc_status,customer_since,risk_category
0,100001,Customer_1,M,54,Bengaluru,Karnataka,Homemaker,230724.0,Verified,2023-03-27,Medium
1,100002,Customer_2,Male,32,Pune,Maharashtra,Business Owner,2097413.0,Verified,2024-08-08,High
2,100003,Customer_3,Female,47,Pune,Maharashtra,Government,1413965.0,Verified,2024-08-03,High
3,100004,Customer_4,Male,71,Bengaluru,Karnataka,Salaried,1256024.0,Verified,2022-11-14,Low
4,100005,Customer_5,Female,59,Mumbai,Maharashtra,Freelancer,1276311.0,Verified,2024-11-22,Medium
5,100006,Customer_6,F,61,Pune,Maharashtra,Salaried,1793411.0,Verified,2023-03-31,High
6,100007,Customer_7,M,43,Delhi,Delhi,Business Owner,3480589.0,Verified,2024-12-10,Low
7,100008,Customer_8,Male,43,Delhi,Delhi,Student,124722.0,Verified,2023-10-02,High
8,100009,Customer_9,F,39,Mumbai,Maharashtra,Self-Employed,1135216.0,Verified,2025-04-10,High
9,100010,Customer_10,F,66,Kolkata,West Bengal,Student,NaN,Verified,2025-07-30,Low

In [5]:
print(f"Customers before duplicate removal: {len(clean_customers)}")
clean_customers = clean_customers.drop_duplicates(subset=['customer_name'], keep='first')
print(f"Customers after duplicate removal: {len(clean_customers)}\n")

Customers before duplicate removal: 25134
Customers after duplicate removal: 25000

In [6]:
clean_customers['customer_since'] = pd.to_datetime(clean_customers['customer_since'])

In [7]:
clean_customers['annual_income'] = clean_customers.groupby('occupation')['annual_income'].transform(lambda x: x.fillna(x.median()))

clean_customers['risk_category'] = clean_customers['risk_category'].fillna('Unknown')

In [8]:
clean_customers['gender'].unique()

array(['M', 'Male', 'Female', 'F'], dtype=object)

In [9]:
clean_customers['gender'] = clean_customers['gender'].map({'M': 'Male', 'F': 'Female', 'Male': 'Male', 'Female': 'Female'})
clean_customers['city'] = clean_customers['city'].str.strip().str.title()

In [10]:
clean_customers['age'] = np.where(clean_customers['age'] < 18, 18, clean_customers['age'])

In [11]:
Q1_age = clean_customers['age'].quantile(0.25)
Q3_age = clean_customers['age'].quantile(0.75)
IQR_age = Q3_age - Q1_age
lower_age = Q1_age - 1.5 * IQR_age
upper_age = Q3_age + 1.5 * IQR_age

clean_customers['age_outlier_flag'] = ((clean_customers['age'] < lower_age) | (clean_customers['age'] > upper_age)).astype(int)
print(f"Age outliers detected: {clean_customers['age_outlier_flag'].sum()}")

upper_limit_age = clean_customers['age'].quantile(0.95)
upper_limit_age

Age outliers detected: 0

np.float64(78.0)

In [12]:
(clean_customers['age']>80).sum()

np.int64(127)

In [13]:
clean_customers['age_outlier_flag'] = (clean_customers['age'] > 80).astype(int)

In [14]:
clean_customers['age_outlier_flag'].sum()

np.int64(127)

In [15]:
clean_customers.head()

,customer_id,customer_name,gender,age,city,state,occupation,annual_income,kyc_status,customer_since,risk_category,age_outlier_flag
0,100001,Customer_1,Male,54,Bengaluru,Karnataka,Homemaker,230724.0,Verified,2023-03-27,Medium,0
1,100002,Customer_2,Male,32,Pune,Maharashtra,Business Owner,2097413.0,Verified,2024-08-08,High,0
2,100003,Customer_3,Female,47,Pune,Maharashtra,Government,1413965.0,Verified,2024-08-03,High,0
3,100004,Customer_4,Male,71,Bengaluru,Karnataka,Salaried,1256024.0,Verified,2022-11-14,Low,0
4,100005,Customer_5,Female,59,Mumbai,Maharashtra,Freelancer,1276311.0,Verified,2024-11-22,Medium,0

In [16]:
clean_customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25000 entries, 0 to 24999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       25000 non-null  int64
 1   customer_name     25000 non-null  object
 2   gender            25000 non-null  object
 3   age               25000 non-null  int64
 4   city              25000 non-null  object
 5   state             25000 non-null  object
 6   occupation        25000 non-null  object
 7   annual_income     25000 non-null  float64
 8   kyc_status        25000 non-null  object
 9   customer_since    25000 non-null  datetime64[ns]
 10  risk_category     25000 non-null  object
 11  age_outlier_flag  25000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(7)
memory usage: 2.5+ MB

In [17]:
clean_customers.describe()

,customer_id,age,annual_income,customer_since,age_outlier_flag
count,25000.000000,25000.000000,2.500000e+04,25000,25000.000000
mean,112500.500000,49.215440,9.493731e+05,2024-05-24 01:47:56.544000,0.005080
min,100001.000000,18.000000,6.300000e+01,2022-04-13 00:00:00,0.000000
25%,106250.750000,33.000000,2.360315e+05,2023-04-25 00:00:00,0.000000
50%,112500.500000,49.000000,7.206135e+05,2024-05-10 00:00:00,0.000000
75%,118750.250000,65.000000,1.367275e+06,2025-05-18 00:00:00,0.000000
max,125000.000000,105.000000,3.499778e+06,2030-05-15 00:00:00,1.000000
std,7217.022701,18.607491,8.472648e+05,NaN,0.071094

# Cleaning Transactions Table

In [18]:
clean_transactions = transactions.copy()
clean_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150751 entries, 0 to 150750
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        150751 non-null  int64
 1   customer_id           150751 non-null  int64
 2   account_id            150751 non-null  int64
 3   card_id               45059 non-null   float64
 4   transaction_datetime  150751 non-null  datetime64[ns]
 5   transaction_amount    150751 non-null  float64
 6   transaction_type      150751 non-null  object
 7   channel               150751 non-null  object
 8   merchant_id           57251 non-null   float64
 9   transaction_city      150751 non-null  object
 10  transaction_status    150751 non-null  object
 11  is_fraud              150751 non-null  object
 12  fraud_type            12096 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(3), object(6)
memory usage: 15.0+ MB

In [19]:
clean_transactions.describe()

,transaction_id,customer_id,account_id,card_id,transaction_datetime,transaction_amount,merchant_id
count,1.507510e+05,150751.000000,150751.000000,45059.000000,150751,150751.000000,57251.000000
mean,1.027427e+07,112493.752406,715030.381404,907497.129364,2025-06-06 15:18:04.951655424,17568.578683,4900.425827
min,1.000000e+07,100001.000000,700001.000000,900001.000000,2024-05-21 22:30:53,-15095.000000,3001.000000
25%,1.003769e+07,106267.000000,707507.500000,903759.500000,2024-11-20 13:10:29.500000,3605.000000,3497.000000
50%,1.007538e+07,112513.000000,715033.000000,907500.000000,2025-05-24 13:43:17,7569.000000,4012.000000
75%,1.011306e+07,118713.000000,722590.500000,911219.000000,2025-11-24 15:13:26.500000,11502.000000,4528.000000
max,5.014997e+07,125000.000000,730000.000000,915000.000000,2030-01-01 12:00:00,999999.990000,99999.000000
std,2.816520e+06,7209.773617,8668.655009,4313.937290,NaN,95436.294865,9263.285073

In [20]:
print(f"Transactions before duplicate removal: {len(clean_transactions)}")

cols_to_check = [col for col in clean_transactions.columns if col != 'transaction_id']
clean_transactions = clean_transactions.drop_duplicates(subset=cols_to_check, keep='first')

print(f"Transactions after duplicate removal: {len(clean_transactions)}")

Transactions before duplicate removal: 150751
Transactions after duplicate removal: 150000

In [21]:
clean_transactions.head(10)

,transaction_id,customer_id,account_id,card_id,transaction_datetime,transaction_amount,transaction_type,channel,merchant_id,transaction_city,transaction_status,is_fraud,fraud_type
0,10000001,105956,713605,NaN,2025-09-02 04:10:25,8840.0,Deposit,NetBanking,NaN,Kolkata,Failed,b'\x00',None
1,10000002,123612,700598,904074.0,2024-06-04 23:11:25,3497.0,Deposit,NetBanking,NaN,Bengaluru,Success,b'\x00',None
2,10000003,120244,716032,909156.0,2024-10-24 02:38:25,14589.0,Deposit,NetBanking,NaN,Pune,Success,b'\x00',None
3,10000004,108649,711947,NaN,2024-05-23 02:43:25,4254.0,Withdrawal,POS,3908.0,Pune,Success,b'\x00',None
4,10000005,116450,708892,NaN,2024-12-04 22:51:25,10570.0,Deposit,ATM,NaN,Chennai,Success,b'\x00',None
5,10000006,119627,715598,909933.0,2024-08-01 08:07:25,11764.0,Transfer,UPI,NaN,Bengaluru,Success,b'\x00',None
6,10000007,124660,712615,906827.0,2024-08-30 10:48:25,11723.0,Withdrawal,NetBanking,NaN,Chennai,Success,b'\x00',None
7,10000008,112366,726881,NaN,2025-06-08 03:29:25,7645.0,Purchase,UPI,NaN,Hyderabad,Success,b'\x00',None
8,10000009,119043,718986,NaN,2024-09-09 01:42:25,11403.0,Purchase,POS,3781.0,Bengaluru,Success,b'\x00',None
9,10000010,121381,704497,907037.0,2025-04-05 10:22:25,6637.0,Withdrawal,UPI,NaN,Pune,Success,b'\x00',None

In [22]:
clean_transactions['is_fraud'].unique()

array([b'\x00', b'\x01'], dtype=object)

In [23]:
clean_transactions['channel'].unique()

array(['NetBanking', 'POS', 'ATM', 'UPI', 'Card', 'INVALID_CH'],
      dtype=object)

In [24]:
clean_transactions['transaction_status'] = clean_transactions['transaction_status'].str.strip().str.title()

clean_transactions['is_fraud'] = clean_transactions['is_fraud'].apply(
    lambda x: 1 if str(x).strip() in ["b'\\x01'"] else 0
)

clean_transactions['channel'] = clean_transactions['channel'].replace({'INVALID_CH': 'Unknown'})

In [25]:
clean_transactions['transaction_amount'] = clean_transactions['transaction_amount'].abs()

In [26]:
Q1_txn = clean_transactions['transaction_amount'].quantile(0.25)
Q3_txn = clean_transactions['transaction_amount'].quantile(0.75)
IQR_txn = Q3_txn - Q1_txn
lower_txn = Q1_txn - 1.5 * IQR_txn
upper_txn = Q3_txn + 1.5 * IQR_txn

clean_transactions['txn_outlier_flag'] = ((clean_transactions['transaction_amount'] < lower_txn) | (clean_transactions['transaction_amount'] > upper_txn)).astype(int)
print(f"Transaction Amount outliers detected: {clean_transactions['txn_outlier_flag'].sum()}")

upper_limit_txn = clean_transactions['transaction_amount'].quantile(0.95)
upper_limit_txn

Transaction Amount outliers detected: 3219

np.float64(14650.0)

In [27]:
clean_transactions = clean_transactions[clean_transactions['transaction_amount'] != 999999.99]

In [28]:
clean_transactions['card_id'] = clean_transactions['card_id'].astype('Int64')
clean_transactions['merchant_id'] = clean_transactions['merchant_id'].astype('Int64')

In [29]:
clean_transactions.head(10)

,transaction_id,customer_id,account_id,card_id,transaction_datetime,transaction_amount,transaction_type,channel,merchant_id,transaction_city,transaction_status,is_fraud,fraud_type,txn_outlier_flag
0,10000001,105956,713605,<NA>,2025-09-02 04:10:25,8840.0,Deposit,NetBanking,<NA>,Kolkata,Failed,0,None,0
1,10000002,123612,700598,904074,2024-06-04 23:11:25,3497.0,Deposit,NetBanking,<NA>,Bengaluru,Success,0,None,0
2,10000003,120244,716032,909156,2024-10-24 02:38:25,14589.0,Deposit,NetBanking,<NA>,Pune,Success,0,None,0
3,10000004,108649,711947,<NA>,2024-05-23 02:43:25,4254.0,Withdrawal,POS,3908,Pune,Success,0,None,0
4,10000005,116450,708892,<NA>,2024-12-04 22:51:25,10570.0,Deposit,ATM,<NA>,Chennai,Success,0,None,0
5,10000006,119627,715598,909933,2024-08-01 08:07:25,11764.0,Transfer,UPI,<NA>,Bengaluru,Success,0,None,0
6,10000007,124660,712615,906827,2024-08-30 10:48:25,11723.0,Withdrawal,NetBanking,<NA>,Chennai,Success,0,None,0
7,10000008,112366,726881,<NA>,2025-06-08 03:29:25,7645.0,Purchase,UPI,<NA>,Hyderabad,Success,0,None,0
8,10000009,119043,718986,<NA>,2024-09-09 01:42:25,11403.0,Purchase,POS,3781,Bengaluru,Success,0,None,0
9,10000010,121381,704497,907037,2025-04-05 10:22:25,6637.0,Withdrawal,UPI,<NA>,Pune,Success,0,None,0

In [30]:
clean_transactions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148614 entries, 0 to 149999
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        148614 non-null  int64
 1   customer_id           148614 non-null  int64
 2   account_id            148614 non-null  int64
 3   card_id               44390 non-null   Int64
 4   transaction_datetime  148614 non-null  datetime64[ns]
 5   transaction_amount    148614 non-null  float64
 6   transaction_type      148614 non-null  object
 7   channel               148614 non-null  object
 8   merchant_id           56426 non-null   Int64
 9   transaction_city      148614 non-null  object
 10  transaction_status    148614 non-null  object
 11  is_fraud              148614 non-null  int64
 12  fraud_type            12044 non-null   object
 13  txn_outlier_flag      148614 non-null  int64
dtypes: Int64(2), datetime64[ns](1), float64(1), int64(5), object(5)
memory usage: 17.3+ MB

In [31]:
clean_transactions.describe()

,transaction_id,customer_id,account_id,card_id,transaction_datetime,transaction_amount,merchant_id,is_fraud,txn_outlier_flag
count,1.486140e+05,148614.000000,148614.000000,44390.0,148614,148614.000000,56426.0,148614.000000,148614.000000
mean,1.007500e+07,112494.797563,715029.940342,907502.792566,2025-06-06 12:05:43.049383168,8556.101888,4903.500638,0.081042,0.012334
min,1.000000e+07,100001.000000,700001.000000,900001.0,2024-05-21 22:30:53,5.000000,3001.0,0.000000,0.000000
25%,1.003751e+07,106266.000000,707509.000000,903766.25,2024-11-20 11:37:37.500000,3674.000000,3498.0,0.000000,0.000000
50%,1.007500e+07,112516.000000,715032.000000,907505.0,2025-05-24 13:02:39,7566.000000,4012.0,0.000000,0.000000
75%,1.011250e+07,118713.000000,722591.000000,911225.75,2025-11-24 13:24:01.249999872,11428.000000,4529.0,0.000000,0.000000
max,1.015000e+07,125000.000000,730000.000000,915000.0,2030-01-01 12:00:00,124994.000000,99999.0,1.000000,1.000000
std,4.330219e+04,7210.289457,8668.201217,4313.100144,NaN,10860.360598,9278.172303,0.272901,0.110372

# Cleaning Merchants Table

In [32]:
clean_merchants = merchants.copy()
clean_merchants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   merchant_id        2000 non-null   int64
 1   merchant_name      2000 non-null   object
 2   merchant_category  2000 non-null   object
 3   merchant_city      1920 non-null   object
 4   risk_level         1928 non-null   object
 5   chargeback_rate    2000 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 93.9+ KB

In [33]:
clean_merchants.describe()

       merchant_id  chargeback_rate
count  2000.000000      2000.000000
mean   4000.500000         6.617610
std     577.494589        16.679368
min    3001.000000         0.000000
25%    3500.750000         2.510000
50%    4000.500000         5.185000
75%    4500.250000         7.510000
max    5000.000000       195.090000

In [34]:
print(f"Merchants before duplicate removal: {len(clean_merchants)}")
clean_merchants = clean_merchants.drop_duplicates()
print(f"Merchants after duplicate removal: {len(clean_merchants)}")

Merchants before duplicate removal: 2000
Merchants after duplicate removal: 2000

In [35]:
clean_merchants.head(10)

,merchant_id,merchant_name,merchant_category,merchant_city,risk_level,chargeback_rate
0,3001,Merchant_1,Grocery,Mumbai,High,7.01
1,3002,Merchant_2,Entertainment,Delhi,Low,8.84
2,3003,Merchant_3,Electronics,Delhi,Medium,4.53
3,3004,Merchant_4,Apparel,Kolkata,Medium,3.25
4,3005,Merchant_5,Subscriptions,Bengaluru,None,2.15
5,3006,Merchant_6,Entertainment,Ahmedabad,Low,2.79
6,3007,Merchant_7,Electronics,Kolkata,High,5.72
7,3008,Merchant_8,Subscriptions,Kolkata,Low,3.46
8,3009,Merchant_9,Electronics,Chennai,Low,0.53
9,3010,Merchant_10,Apparel,Delhi,Low,2.71

In [36]:
clean_merchants['merchant_city'] = clean_merchants['merchant_city'].fillna('Unknown')
clean_merchants['merchant_city'] = clean_merchants['merchant_city'].str.strip().str.title()

In [37]:
clean_merchants['risk_level'] = clean_merchants['risk_level'].fillna('Unknown')

In [38]:
clean_merchants['chargeback_rate'] = np.where(clean_merchants['chargeback_rate'] > 100, 100, clean_merchants['chargeback_rate'])

In [39]:
clean_merchants['merchant_category'] = clean_merchants['merchant_category'].replace({'Unknown_Cat': 'Unknown'})

In [40]:
clean_merchants.head(10)

,merchant_id,merchant_name,merchant_category,merchant_city,risk_level,chargeback_rate
0,3001,Merchant_1,Grocery,Mumbai,High,7.01
1,3002,Merchant_2,Entertainment,Delhi,Low,8.84
2,3003,Merchant_3,Electronics,Delhi,Medium,4.53
3,3004,Merchant_4,Apparel,Kolkata,Medium,3.25
4,3005,Merchant_5,Subscriptions,Bengaluru,Unknown,2.15
5,3006,Merchant_6,Entertainment,Ahmedabad,Low,2.79
6,3007,Merchant_7,Electronics,Kolkata,High,5.72
7,3008,Merchant_8,Subscriptions,Kolkata,Low,3.46
8,3009,Merchant_9,Electronics,Chennai,Low,0.53
9,3010,Merchant_10,Apparel,Delhi,Low,2.71

In [41]:
clean_merchants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   merchant_id        2000 non-null   int64
 1   merchant_name      2000 non-null   object
 2   merchant_category  2000 non-null   object
 3   merchant_city      2000 non-null   object
 4   risk_level         2000 non-null   object
 5   chargeback_rate    2000 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 93.9+ KB

In [42]:
clean_merchants.describe()

       merchant_id  chargeback_rate
count  2000.000000      2000.000000
mean   4000.500000         5.916235
std     577.494589         9.646198
min    3001.000000         0.000000
25%    3500.750000         2.510000
50%    4000.500000         5.185000
75%    4500.250000         7.510000
max    5000.000000       100.000000

# Cleaning Branches Table

In [43]:
clean_branches = branches.copy()
clean_branches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   branch_id       250 non-null    int64
 1   branch_name     250 non-null    object
 2   city            250 non-null    object
 3   state           236 non-null    object
 4   region          250 non-null    object
 5   branch_manager  237 non-null    object
 6   opening_date    250 non-null    object
 7   branch_type     250 non-null    object
dtypes: int64(1), object(7)
memory usage: 15.8+ KB

In [44]:
clean_branches.describe()

        branch_id
count  250.000000
mean   125.500000
std     72.312977
min      1.000000
25%     63.250000
50%    125.500000
75%    187.750000
max    250.000000

In [45]:
clean_branches.head(10)

,branch_id,branch_name,city,state,region,branch_manager,opening_date,branch_type
0,1,Branch_1,Hyderabad,Telangana,South,Manager_1,2025-02-20,Urban
1,2,Branch_2,Pune,Maharashtra,South,None,2025-08-15,Metro
2,3,Branch_3,Bengaluru,Karnataka,West,Manager_3,2021-11-15,Urban
3,4,Branch_4,Delhi,Delhi,East,Manager_4,2023-08-16,urban
4,5,Branch_5,Chennai,None,East,None,2024-04-14,Urban
5,6,Branch_6,Hyderabad,Telangana,North,Manager_6,2023-08-04,Urban
6,7,Branch_7,Mumbai,Maharashtra,East,Manager_7,2026-03-01,Semi-Urban
7,8,Branch_8,Hyderabad,Telangana,West,Manager_8,2024-07-15,SEMI-URBAN
8,9,Branch_9,Mumbai,Maharashtra,West,Manager_9,2024-09-30,Metro
9,10,Branch_10,Pune,Maharashtra,South,Manager_10,2025-10-03,Metro

In [46]:
print(f"Branches before duplicate removal: {len(clean_branches)}")
clean_branches = clean_branches.drop_duplicates()
print(f"Branches after duplicate removal: {len(clean_branches)}")

Branches before duplicate removal: 250
Branches after duplicate removal: 250

In [47]:
state_map = {
    'Hyderabad': 'Telangana', 'Bengaluru': 'Karnataka', 'Chennai': 'Tamil Nadu',
    'Pune': 'Maharashtra', 'Mumbai': 'Maharashtra', 'Delhi': 'Delhi',
    'Kolkata': 'West Bengal', 'Ahmedabad': 'Gujarat'
}

clean_branches['state'] = clean_branches['state'].fillna(clean_branches['city'].map(state_map))

In [48]:
clean_branches['branch_manager'] = clean_branches['branch_manager'].fillna('Unassigned')

In [49]:
clean_branches['opening_date'] = pd.to_datetime(clean_branches['opening_date'])

In [50]:
future_dates = clean_branches['opening_date'] > pd.Timestamp.now()
print(f"Found {future_dates.sum()} branches with impossible future opening dates.")

Found 3 branches with impossible future opening dates.

In [51]:
clean_branches.loc[future_dates, 'opening_date'] = pd.Timestamp.now().normalize()

In [52]:
clean_branches['branch_name'] = clean_branches['branch_name'].str.strip().str.title()
clean_branches['branch_type'] = clean_branches['branch_type'].str.strip().str.title()

In [53]:
clean_branches.head(10)

,branch_id,branch_name,city,state,region,branch_manager,opening_date,branch_type
0,1,Branch_1,Hyderabad,Telangana,South,Manager_1,2025-02-20,Urban
1,2,Branch_2,Pune,Maharashtra,South,Unassigned,2025-08-15,Metro
2,3,Branch_3,Bengaluru,Karnataka,West,Manager_3,2021-11-15,Urban
3,4,Branch_4,Delhi,Delhi,East,Manager_4,2023-08-16,Urban
4,5,Branch_5,Chennai,Tamil Nadu,East,Unassigned,2024-04-14,Urban
5,6,Branch_6,Hyderabad,Telangana,North,Manager_6,2023-08-04,Urban
6,7,Branch_7,Mumbai,Maharashtra,East,Manager_7,2026-03-01,Semi-Urban
7,8,Branch_8,Hyderabad,Telangana,West,Manager_8,2024-07-15,Semi-Urban
8,9,Branch_9,Mumbai,Maharashtra,West,Manager_9,2024-09-30,Metro
9,10,Branch_10,Pune,Maharashtra,South,Manager_10,2025-10-03,Metro

In [54]:
clean_branches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   branch_id       250 non-null    int64
 1   branch_name     250 non-null    object
 2   city            250 non-null    object
 3   state           250 non-null    object
 4   region          250 non-null    object
 5   branch_manager  250 non-null    object
 6   opening_date    250 non-null    datetime64[ns]
 7   branch_type     250 non-null    object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 15.8+ KB

In [55]:
clean_branches.describe()

        branch_id                opening_date
count  250.000000                         250
mean   125.500000  2023-11-17 21:18:43.200000
min      1.000000         2020-12-10 00:00:00
25%     63.250000         2022-07-09 18:00:00
50%    125.500000         2024-01-07 00:00:00
75%    187.750000         2025-05-04 00:00:00
max    250.000000         2026-05-26 00:00:00
std     72.312977                         NaN

# Cleaning Accounts Table

In [56]:
clean_accounts = accounts.copy()
clean_accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   account_id           30000 non-null  int64
 1   customer_id          30000 non-null  int64
 2   branch_id            29440 non-null  float64
 3   account_type         30000 non-null  object
 4   account_open_date    30000 non-null  object
 5   account_status       30000 non-null  object
 6   current_balance      30000 non-null  float64
 7   avg_monthly_balance  29101 non-null  float64
dtypes: float64(3), int64(2), object(3)
memory usage: 1.8+ MB

In [57]:
clean_accounts.describe()

,account_id,customer_id,branch_id,current_balance,avg_monthly_balance
count,30000.000000,30000.000000,29440.000000,30000.000000,29101.000000
mean,715000.500000,120808.697700,125.236005,95802.204852,96025.866586
std,8660.398374,85792.543624,71.826315,64008.119600,65512.107921
min,700001.000000,100001.000000,1.000000,-198715.760000,-233395.620000
25%,707500.750000,106331.500000,63.000000,47004.580000,46074.490000
50%,715000.500000,112649.500000,125.000000,97859.505000,96307.990000
75%,722500.250000,118940.000000,187.000000,148436.420000,146406.320000
max,730000.000000,999999.000000,250.000000,199991.050000,239146.140000

In [58]:
print(f"Accounts before duplicate removal: {len(clean_accounts)}")
clean_accounts = clean_accounts.drop_duplicates()
print(f"Accounts after duplicate removal: {len(clean_accounts)}")

Accounts before duplicate removal: 30000
Accounts after duplicate removal: 30000

In [59]:
clean_accounts['account_open_date'] = pd.to_datetime(clean_accounts['account_open_date'])

In [60]:
clean_accounts['branch_id'] = clean_accounts['branch_id'].astype('Int64')

In [61]:
clean_accounts['avg_monthly_balance'] = clean_accounts['avg_monthly_balance'].abs()
clean_accounts['avg_monthly_balance'] = clean_accounts['avg_monthly_balance'].fillna(clean_accounts['current_balance'])

In [62]:
clean_accounts['current_balance'] = clean_accounts['current_balance'].abs()

In [63]:
clean_accounts['account_type'].unique()

array(['Salary', 'CURRENT', 'Current', 'Savings', 'Salry', 'savings'],
      dtype=object)

In [64]:
clean_accounts['account_type'] = clean_accounts['account_type'].replace({'Salry': 'Salary', 'salry': 'Salary'})
clean_accounts['account_type'] = clean_accounts['account_type'].str.strip().str.title()

In [65]:
clean_accounts.head(10)

,account_id,customer_id,branch_id,account_type,account_open_date,account_status,current_balance,avg_monthly_balance
0,700001,104557,176,Salary,2024-03-27,Inactive,1586.41,1835.56
1,700002,111351,218,Current,2025-11-12,Inactive,106038.08,114127.58
2,700003,102322,155,Salary,2026-01-22,Frozen,83537.90,90108.69
3,700004,111323,79,Salary,2023-08-29,Frozen,9328.85,9802.31
4,700005,119870,66,Salary,2025-08-29,Inactive,105618.69,88235.05
5,700006,104710,160,Current,2026-04-29,Frozen,14802.66,17384.97
6,700007,122812,190,Savings,2025-02-10,Active,159361.11,155431.67
7,700008,124851,163,Current,2023-04-05,Inactive,111422.18,104748.54
8,700009,112823,134,Current,2023-08-20,Frozen,51853.08,44786.02
9,700010,120808,146,Current,2026-01-09,Frozen,91251.42,86343.44

In [66]:
clean_accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   account_id           30000 non-null  int64
 1   customer_id          30000 non-null  int64
 2   branch_id            29440 non-null  Int64
 3   account_type         30000 non-null  object
 4   account_open_date    30000 non-null  datetime64[ns]
 5   account_status       30000 non-null  object
 6   current_balance      30000 non-null  float64
 7   avg_monthly_balance  30000 non-null  float64
dtypes: Int64(1), datetime64[ns](1), float64(2), int64(2), object(2)
memory usage: 1.9+ MB

In [67]:
clean_accounts.describe()

,account_id,customer_id,branch_id,account_open_date,current_balance,avg_monthly_balance
count,30000.000000,30000.000000,29440.0,30000,30000.000000,30000.000000
mean,715000.500000,120808.697700,125.236005,2024-05-01 23:09:33.120000256,99773.101255,99793.757361
min,700001.000000,100001.000000,1.0,2022-04-13 00:00:00,7.650000,-195839.980000
25%,707500.750000,106331.500000,63.0,2023-04-27 00:00:00,50099.280000,49129.807500
50%,715000.500000,112649.500000,125.0,2024-05-02 00:00:00,99775.450000,98244.925000
75%,722500.250000,118940.000000,187.0,2025-05-14 00:00:00,149333.720000,147257.827500
max,730000.000000,999999.000000,250.0,2026-05-21 00:00:00,199991.050000,239146.140000
std,8660.398374,85792.543624,71.826315,NaN,57622.948617,59509.893694

# Cleaning Credit Cards Table

In [68]:
clean_credit_cards = credit_cards.copy()
credit_cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   card_id          15000 non-null  int64
 1   customer_id      15000 non-null  int64
 2   card_type        15000 non-null  object
 3   credit_limit     15000 non-null  float64
 4   available_limit  15000 non-null  float64
 5   issue_date       15000 non-null  object
 6   expiry_date      15000 non-null  object
 7   card_status      15000 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 937.6+ KB

In [69]:
credit_cards.describe()

             card_id    customer_id  credit_limit  available_limit
count   15000.000000   15000.000000  1.500000e+04     1.500000e+04
mean   907500.500000  112588.195400  3.558725e+05     1.859656e+05
std      4330.271354    7196.299263  1.011124e+06     6.288762e+05
min    900001.000000  100001.000000  5.001100e+04     9.170000e+00
25%    903750.750000  106297.500000  1.527238e+05     4.850290e+04
50%    907500.500000  112734.500000  2.536080e+05     1.050787e+05
75%    911250.250000  118767.500000  3.547788e+05     1.979859e+05
max    915000.000000  125000.000000  9.999999e+06     1.005000e+07

In [70]:
print(f"Credit Cards before duplicate removal: {len(clean_credit_cards)}")
clean_credit_cards = clean_credit_cards.drop_duplicates()
print(f"Credit Cards after duplicate removal: {len(clean_credit_cards)}")

Credit Cards before duplicate removal: 15000
Credit Cards after duplicate removal: 15000

In [71]:
Q1_credit = clean_credit_cards['credit_limit'].quantile(0.25)
Q3_credit = clean_credit_cards['credit_limit'].quantile(0.75)
IQR_credit = Q3_credit - Q1_credit
lower_credit = Q1_credit - 1.5 * IQR_credit
upper_credit = Q3_credit + 1.5 * IQR_credit

clean_credit_cards['credit_outlier_flag'] = ((clean_credit_cards['credit_limit'] < lower_credit) | (clean_credit_cards['credit_limit'] > upper_credit)).astype(int)
print(f"Credit Limit outliers detected: {clean_credit_cards['credit_outlier_flag'].sum()}")

upper_limit_credit = clean_credit_cards['credit_limit'].quantile(0.95)
upper_limit_credit

Credit Limit outliers detected: 161

np.float64(433423.5)

In [72]:
clean_credit_cards.loc[clean_credit_cards['credit_limit'] > 500000, 'credit_limit'] = 500000

In [73]:
invalid_limits = clean_credit_cards['available_limit'] > clean_credit_cards['credit_limit']
print(f"Found {invalid_limits.sum()} cards with mathematically impossible available limits.")

Found 426 cards with mathematically impossible available limits.

In [74]:
clean_credit_cards['available_limit'] = np.where(invalid_limits, clean_credit_cards['credit_limit'], clean_credit_cards['available_limit'])

In [75]:
clean_credit_cards['card_status'] = clean_credit_cards['card_status'].str.strip().str.title()

In [76]:
clean_credit_cards['issue_date'] = pd.to_datetime(clean_credit_cards['issue_date'])
clean_credit_cards['expiry_date'] = pd.to_datetime(clean_credit_cards['expiry_date'])

In [77]:
clean_credit_cards.head(10)

,card_id,customer_id,card_type,credit_limit,available_limit,issue_date,expiry_date,card_status,credit_outlier_flag
0,900001,104812,Silver,435779.0,13053.58,2026-01-17,2031-01-17,Active,0
1,900002,116604,Business,129991.0,75419.80,2023-12-31,2028-12-31,Active,0
2,900003,120040,Business,243520.0,141377.46,2024-08-10,2029-08-10,Active,0
3,900004,101505,Business,370900.0,141235.64,2023-09-15,2028-09-15,Active,0
4,900005,124819,Platinum,385326.0,219440.83,2024-06-22,2029-06-22,Active,0
5,900006,115874,Business,352269.0,70114.52,2024-02-05,2029-02-05,Active,0
6,900007,101077,Gold,361658.0,318219.13,2023-09-11,2028-09-11,Active,0
7,900008,109855,Gold,141513.0,60064.83,2025-10-07,2030-10-07,Active,0
8,900009,104612,Silver,175327.0,98968.05,2025-05-09,2030-05-09,Active,0
9,900010,120366,Silver,121031.0,81305.43,2024-10-24,2029-10-24,Active,0

In [78]:
clean_credit_cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   card_id              15000 non-null  int64
 1   customer_id          15000 non-null  int64
 2   card_type            15000 non-null  object
 3   credit_limit         15000 non-null  float64
 4   available_limit      15000 non-null  float64
 5   issue_date           15000 non-null  datetime64[ns]
 6   expiry_date          15000 non-null  datetime64[ns]
 7   card_status          15000 non-null  object
 8   credit_outlier_flag  15000 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(3), object(2)
memory usage: 1.0+ MB

In [79]:
clean_credit_cards.describe()

,card_id,customer_id,credit_limit,available_limit,issue_date,expiry_date,credit_outlier_flag
count,15000.000000,15000.000000,15000.000000,15000.000000,15000,15000,15000.000000
mean,907500.500000,112588.195400,253905.821067,133133.333062,2025-01-10 11:37:03.360000,2029-11-29 00:00:28.800000,0.010733
min,900001.000000,100001.000000,50011.000000,9.170000,2023-08-26 00:00:00,2026-02-10 00:00:00,0.000000
25%,903750.750000,106297.500000,152723.750000,48502.900000,2024-05-07 18:00:00,2029-04-13 00:00:00,0.000000
50%,907500.500000,112734.500000,253608.000000,104299.200000,2025-01-13 00:00:00,2029-12-28 00:00:00,0.000000
75%,911250.250000,118767.500000,354778.750000,196963.562500,2025-09-18 00:00:00,2030-09-11 00:00:00,0.000000
max,915000.000000,125000.000000,500000.000000,500000.000000,2026-05-21 00:00:00,2031-05-21 00:00:00,1.000000
std,4330.271354,7196.299263,117604.428877,106826.556430,NaN,NaN,0.103048

# Cleaning ATM Logs Table

In [80]:
clean_atm_logs = atm_logs.copy()
clean_atm_logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   atm_log_id            40000 non-null  int64
 1   customer_id           40000 non-null  int64
 2   account_id            40000 non-null  int64
 3   atm_id                40000 non-null  object
 4   atm_city              40000 non-null  object
 5   withdrawal_amount     40000 non-null  float64
 6   attempt_status        40000 non-null  object
 7   attempt_datetime      40000 non-null  datetime64[ns]
 8   failed_attempt_count  40000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 2.7+ MB

In [81]:
clean_atm_logs.describe()

,atm_log_id,customer_id,account_id,withdrawal_amount,attempt_datetime,failed_attempt_count
count,4.000000e+04,40000.000000,40000.000000,40000.000000,40000,40000.000000
mean,5.020000e+06,112396.678200,714970.723625,12624.534075,2025-11-18 22:18:38.338225152,1.467375
min,5.000001e+06,100001.000000,700003.000000,501.000000,2025-05-21 22:48:22,0.000000
25%,5.010001e+06,106115.000000,707477.000000,4306.000000,2025-08-19 21:29:41.750000128,0.000000
50%,5.020000e+06,112345.500000,714933.000000,8107.000000,2025-11-18 12:41:31,1.000000
75%,5.030000e+06,118648.000000,722506.250000,11918.000000,2026-02-17 01:28:12.750000128,2.000000
max,5.040000e+06,125000.000000,730000.000000,500000.000000,2026-05-21 21:53:53,25.000000
std,1.154715e+04,7226.244899,8673.311813,47546.212126,NaN,3.533235

In [82]:
print(f"ATM Logs before duplicate removal: {len(clean_atm_logs)}")
clean_atm_logs = clean_atm_logs.drop_duplicates()
print(f"ATM Logs after duplicate removal: {len(clean_atm_logs)}")

ATM Logs before duplicate removal: 40000
ATM Logs after duplicate removal: 40000

In [83]:
clean_atm_logs.head(10)

,atm_log_id,customer_id,account_id,atm_id,atm_city,withdrawal_amount,attempt_status,attempt_datetime,failed_attempt_count
0,5000001,117968,715465,ATM_BLR_310,Bengaluru,8538.0,Success,2025-09-11 02:32:47,2
1,5000002,107113,717363,ATM_BLR_120,Bengaluru,3591.0,Success,2025-06-09 22:57:47,2
2,5000003,104239,706542,ATM_DEL_390,Delhi,8373.0,Success,2026-03-06 07:39:47,0
3,5000004,114761,725953,ATM_BLR_377,Bengaluru,3727.0,Success,2026-05-11 08:14:47,2
4,5000005,121142,726981,ATM_MAA_579,Chennai,9857.0,Success,2025-08-11 13:41:47,1
5,5000006,102915,705711,ATM_BOM_401,Mumbai,6349.0,Success,2026-04-04 04:11:47,0
6,5000007,110996,714336,ATM_MAA_134,Chennai,6030.0,Failed,2025-06-24 20:24:47,1
7,5000008,101475,707863,ATM_PNQ_166,Pune,562.0,Success,2025-09-16 14:31:47,0
8,5000009,116734,711918,ATM_BOM_589,Mumbai,8927.0,Success,2025-09-26 18:02:47,0
9,5000010,107936,719303,ATM_CCU_232,Kolkata,3123.0,Success,2026-01-27 02:52:47,1

In [84]:
Q1_with = clean_atm_logs['withdrawal_amount'].quantile(0.25)
Q3_with = clean_atm_logs['withdrawal_amount'].quantile(0.75)
IQR_with = Q3_with - Q1_with
lower_with = Q1_with - 1.5 * IQR_with
upper_with = Q3_with + 1.5 * IQR_with

clean_atm_logs['withdrawal_outlier_flag'] = ((clean_atm_logs['withdrawal_amount'] < lower_with) | (clean_atm_logs['withdrawal_amount'] > upper_with)).astype(int)
print(f"Withdrawal Amount outliers detected: {clean_atm_logs['withdrawal_outlier_flag'].sum()}")

upper_limit_with = clean_atm_logs['withdrawal_amount'].quantile(0.95)
upper_limit_with

Withdrawal Amount outliers detected: 374

np.float64(14897.049999999996)

In [85]:
clean_atm_logs['failed_attempt_count'] = np.where(clean_atm_logs['failed_attempt_count'] > 3, 3, clean_atm_logs['failed_attempt_count'])

In [86]:
clean_atm_logs['attempt_status'] = clean_atm_logs['attempt_status'].str.strip().str.title()

In [87]:
clean_atm_logs.head(10)

,atm_log_id,customer_id,account_id,atm_id,atm_city,withdrawal_amount,attempt_status,attempt_datetime,failed_attempt_count,withdrawal_outlier_flag
0,5000001,117968,715465,ATM_BLR_310,Bengaluru,8538.0,Success,2025-09-11 02:32:47,2,0
1,5000002,107113,717363,ATM_BLR_120,Bengaluru,3591.0,Success,2025-06-09 22:57:47,2,0
2,5000003,104239,706542,ATM_DEL_390,Delhi,8373.0,Success,2026-03-06 07:39:47,0,0
3,5000004,114761,725953,ATM_BLR_377,Bengaluru,3727.0,Success,2026-05-11 08:14:47,2,0
4,5000005,121142,726981,ATM_MAA_579,Chennai,9857.0,Success,2025-08-11 13:41:47,1,0
5,5000006,102915,705711,ATM_BOM_401,Mumbai,6349.0,Success,2026-04-04 04:11:47,0,0
6,5000007,110996,714336,ATM_MAA_134,Chennai,6030.0,Failed,2025-06-24 20:24:47,1,0
7,5000008,101475,707863,ATM_PNQ_166,Pune,562.0,Success,2025-09-16 14:31:47,0,0
8,5000009,116734,711918,ATM_BOM_589,Mumbai,8927.0,Success,2025-09-26 18:02:47,0,0
9,5000010,107936,719303,ATM_CCU_232,Kolkata,3123.0,Success,2026-01-27 02:52:47,1,0

In [88]:
clean_atm_logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   atm_log_id               40000 non-null  int64
 1   customer_id              40000 non-null  int64
 2   account_id               40000 non-null  int64
 3   atm_id                   40000 non-null  object
 4   atm_city                 40000 non-null  object
 5   withdrawal_amount        40000 non-null  float64
 6   attempt_status           40000 non-null  object
 7   attempt_datetime         40000 non-null  datetime64[ns]
 8   failed_attempt_count     40000 non-null  int64
 9   withdrawal_outlier_flag  40000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 3.1+ MB

In [89]:
clean_atm_logs.describe()

,atm_log_id,customer_id,account_id,withdrawal_amount,attempt_datetime,failed_attempt_count,withdrawal_outlier_flag
count,4.000000e+04,40000.000000,40000.000000,40000.000000,40000,40000.000000,40000.000000
mean,5.020000e+06,112396.678200,714970.723625,12624.534075,2025-11-18 22:18:38.338225152,1.007575,0.009350
min,5.000001e+06,100001.000000,700003.000000,501.000000,2025-05-21 22:48:22,0.000000,0.000000
25%,5.010001e+06,106115.000000,707477.000000,4306.000000,2025-08-19 21:29:41.750000128,0.000000,0.000000
50%,5.020000e+06,112345.500000,714933.000000,8107.000000,2025-11-18 12:41:31,1.000000,0.000000
75%,5.030000e+06,118648.000000,722506.250000,11918.000000,2026-02-17 01:28:12.750000128,2.000000,0.000000
max,5.040000e+06,125000.000000,730000.000000,500000.000000,2026-05-21 21:53:53,3.000000,1.000000
std,1.154715e+04,7226.244899,8673.311813,47546.212126,NaN,0.864313,0.096243

# Cleaning Fraud Alerts Table

In [90]:
clean_fraud_alerts = fraud_alerts.copy()
clean_fraud_alerts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   alert_id              8000 non-null   int64
 1   transaction_id        8000 non-null   int64
 2   alert_type            7601 non-null   object
 3   risk_score            8000 non-null   int64
 4   alert_status          8000 non-null   object
 5   investigation_result  7579 non-null   object
 6   created_datetime      8000 non-null   datetime64[ns]
 7   resolved_datetime     8000 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3), object(3)
memory usage: 500.1+ KB

In [91]:
clean_fraud_alerts.describe()

,alert_id,transaction_id,risk_score,created_datetime,resolved_datetime
count,8.000000e+03,8.000000e+03,8000.000000,8000,8000
mean,8.004000e+06,1.007572e+07,55.003875,2025-10-24 22:56:25.440999936,2025-10-25 21:06:24.391000064
min,8.000001e+06,1.000002e+07,10.000000,2025-03-31 08:33:47,2025-03-31 05:33:59
25%,8.002001e+06,1.003784e+07,32.000000,2025-07-15 16:18:42.500000,2025-07-16 14:34:05.750000128
50%,8.004000e+06,1.007608e+07,55.000000,2025-10-24 08:03:53,2025-10-24 23:33:47
75%,8.006000e+06,1.011358e+07,77.000000,2026-02-03 09:49:06.750000128,2026-02-04 08:49:16.249999872
max,8.008000e+06,1.014998e+07,150.000000,2026-05-21 20:34:22,2026-05-23 11:34:00
std,2.309545e+03,4.347555e+04,27.520756,NaN,NaN

In [92]:
print(f"Fraud Alerts before duplicate removal: {len(clean_fraud_alerts)}")
clean_fraud_alerts = clean_fraud_alerts.drop_duplicates()
print(f"Fraud Alerts after duplicate removal: {len(clean_fraud_alerts)}")

Fraud Alerts before duplicate removal: 8000
Fraud Alerts after duplicate removal: 8000

In [93]:
clean_fraud_alerts.head(10)

,alert_id,transaction_id,alert_type,risk_score,alert_status,investigation_result,created_datetime,resolved_datetime
0,8000001,10031856,Location Mismatch,41,Investigating,Not Fraud,2026-05-10 23:33:42,2026-05-12 18:33:42
1,8000002,10105411,High Amount,78,Closed,Fraud,2026-01-21 02:33:42,2026-01-22 09:33:42
2,8000003,10021628,Suspicious Login,72,Investigating,Fraud,2026-05-11 07:33:42,2026-05-12 05:33:42
3,8000004,10139649,Location Mismatch,27,Investigating,Pending,2026-01-28 12:33:42,2026-01-28 14:33:42
4,8000005,10064275,High Frequency,69,Closed,Fraud,2026-04-04 07:33:42,2026-04-05 06:33:42
5,8000006,10042870,High Amount,51,Closed,Not Fraud,2025-10-06 17:33:42,2025-10-08 13:33:42
6,8000007,10105077,Suspicious Login,82,Open,Fraud,2026-01-18 03:33:42,2026-01-18 23:33:42
7,8000008,10104883,High Frequency,67,Open,Fraud,2025-12-10 04:33:42,2025-12-11 17:33:42
8,8000009,10123674,High Frequency,23,Investigating,Not Fraud,2026-02-14 08:33:42,2026-02-15 06:33:42
9,8000010,10117378,High Frequency,12,Open,Fraud,2026-05-07 07:33:42,2026-05-08 17:33:42

In [94]:
clean_fraud_alerts['alert_type'].unique()

array(['Location Mismatch', 'High Amount', 'Suspicious Login',
       'High Frequency', None], dtype=object)

In [95]:
clean_fraud_alerts['alert_type'] = clean_fraud_alerts['alert_type'].fillna('Unknown')

clean_fraud_alerts['investigation_result'] = clean_fraud_alerts['investigation_result'].fillna('Pending')

In [96]:
clean_fraud_alerts['risk_score'] = np.where(clean_fraud_alerts['risk_score'] > 100, 100, clean_fraud_alerts['risk_score'])

In [97]:
invalid_dates = clean_fraud_alerts['resolved_datetime'] < clean_fraud_alerts['created_datetime']
print(f"Found {invalid_dates.sum()} alerts with impossible resolution dates (time travel).")

Found 182 alerts with impossible resolution dates (time travel).

In [98]:
clean_fraud_alerts.loc[invalid_dates, 'alert_status'] = 'Investigating'
clean_fraud_alerts.loc[invalid_dates, 'resolved_datetime'] = pd.NaT

In [99]:
clean_fraud_alerts['alert_type'] = clean_fraud_alerts['alert_type'].str.title()
clean_fraud_alerts['alert_status'] = clean_fraud_alerts['alert_status'].str.title()
clean_fraud_alerts['investigation_result'] = clean_fraud_alerts['investigation_result'].str.title()

In [100]:
clean_fraud_alerts.head(10)

,alert_id,transaction_id,alert_type,risk_score,alert_status,investigation_result,created_datetime,resolved_datetime
0,8000001,10031856,Location Mismatch,41,Investigating,Not Fraud,2026-05-10 23:33:42,2026-05-12 18:33:42
1,8000002,10105411,High Amount,78,Closed,Fraud,2026-01-21 02:33:42,2026-01-22 09:33:42
2,8000003,10021628,Suspicious Login,72,Investigating,Fraud,2026-05-11 07:33:42,2026-05-12 05:33:42
3,8000004,10139649,Location Mismatch,27,Investigating,Pending,2026-01-28 12:33:42,2026-01-28 14:33:42
4,8000005,10064275,High Frequency,69,Closed,Fraud,2026-04-04 07:33:42,2026-04-05 06:33:42
5,8000006,10042870,High Amount,51,Closed,Not Fraud,2025-10-06 17:33:42,2025-10-08 13:33:42
6,8000007,10105077,Suspicious Login,82,Open,Fraud,2026-01-18 03:33:42,2026-01-18 23:33:42
7,8000008,10104883,High Frequency,67,Open,Fraud,2025-12-10 04:33:42,2025-12-11 17:33:42
8,8000009,10123674,High Frequency,23,Investigating,Not Fraud,2026-02-14 08:33:42,2026-02-15 06:33:42
9,8000010,10117378,High Frequency,12,Open,Fraud,2026-05-07 07:33:42,2026-05-08 17:33:42

In [101]:
clean_fraud_alerts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   alert_id              8000 non-null   int64
 1   transaction_id        8000 non-null   int64
 2   alert_type            8000 non-null   object
 3   risk_score            8000 non-null   int64
 4   alert_status          8000 non-null   object
 5   investigation_result  8000 non-null   object
 6   created_datetime      8000 non-null   datetime64[ns]
 7   resolved_datetime     7818 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(3), object(3)
memory usage: 500.1+ KB

In [102]:
clean_fraud_alerts.describe()

,alert_id,transaction_id,risk_score,created_datetime,resolved_datetime
count,8.000000e+03,8.000000e+03,8000.000000,8000,7818
mean,8.004000e+06,1.007572e+07,54.535125,2025-10-24 22:56:25.440999936,2025-10-25 16:51:26.911870208
min,8.000001e+06,1.000002e+07,10.000000,2025-03-31 08:33:47,2025-03-31 22:34:27
25%,8.002001e+06,1.003784e+07,32.000000,2025-07-15 16:18:42.500000,2025-07-16 02:33:49.500000
50%,8.004000e+06,1.007608e+07,55.000000,2025-10-24 08:03:53,2025-10-24 16:03:58.500000
75%,8.006000e+06,1.011358e+07,77.000000,2026-02-03 09:49:06.750000128,2026-02-04 04:18:43
max,8.008000e+06,1.014998e+07,100.000000,2026-05-21 20:34:22,2026-05-23 11:34:00
std,2.309545e+03,4.347555e+04,26.297200,NaN,NaN

# Cleaning Device Logins

In [103]:
clean_device_logins = device_logins.copy()
clean_device_logins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   login_id        60000 non-null  int64
 1   customer_id     60000 non-null  int64
 2   device_id       58256 non-null  object
 3   ip_address      60000 non-null  object
 4   login_city      60000 non-null  object
 5   login_datetime  60000 non-null  datetime64[ns]
 6   login_status    60000 non-null  object
 7   device_type     60000 non-null  object
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 3.7+ MB

In [104]:
clean_device_logins.describe()

           login_id    customer_id                 login_datetime
count  6.000000e+04   60000.000000                          60000
mean   6.030000e+06  112501.142367  2025-05-25 10:57:41.620466944
min    6.000001e+06  100002.000000            2024-05-22 22:19:06
25%    6.015001e+06  106244.750000     2024-11-20 22:27:53.500000
50%    6.030000e+06  112494.000000            2025-05-23 22:25:43
75%    6.045000e+06  118753.000000  2025-11-26 22:20:27.249999872
max    6.060000e+06  125000.000000            2026-06-19 22:28:24
std    1.732065e+04    7216.678517                            NaN

In [105]:
print(f"Device Logins before duplicate removal: {len(clean_device_logins)}")
clean_device_logins = clean_device_logins.drop_duplicates()
print(f"Device Logins after duplicate removal: {len(clean_device_logins)}")

Device Logins before duplicate removal: 60000
Device Logins after duplicate removal: 60000

In [106]:
clean_device_logins['device_id'] = clean_device_logins['device_id'].fillna('Unknown_Device')

In [107]:
invalid_ips = clean_device_logins['ip_address'] == '999.999.999.999'
print(f"Found {invalid_ips.sum()} logins with mathematically impossible IPv4 addresses.")

Found 1240 logins with mathematically impossible IPv4 addresses.

In [108]:
clean_device_logins.loc[invalid_ips, 'ip_address'] = 'Unknown_IP'

In [109]:
clean_device_logins['login_datetime'] = pd.to_datetime(clean_device_logins['login_datetime'])
future_logins = clean_device_logins['login_datetime'] > pd.Timestamp.now()
print(f"Found {future_logins.sum()} logins occurring in the future.")

Found 470 logins occurring in the future.

In [110]:
clean_device_logins.loc[future_logins, 'login_datetime'] = pd.Timestamp.now().normalize()

In [111]:
clean_device_logins['login_status'] = clean_device_logins['login_status'].str.title()

In [112]:
clean_device_logins.head(10)

,login_id,customer_id,device_id,ip_address,login_city,login_datetime,login_status,device_type
0,6000001,105314,Unknown_Device,103.21.16.113,Ahmedabad,2025-12-24 22:22:34,Success,Desktop
1,6000002,123290,DEV_99502,103.21.100.149,Delhi,2025-03-31 22:22:34,Success,Tablet
2,6000003,118056,DEV_76175,103.21.160.82,Ahmedabad,2026-03-14 22:22:34,Failed,Tablet
3,6000004,108478,DEV_69424,103.21.134.238,Ahmedabad,2025-01-09 22:22:34,Success,Mobile
4,6000005,117731,DEV_22502,103.21.165.230,Hyderabad,2025-12-12 22:22:34,Success,Desktop
5,6000006,112058,DEV_56036,103.21.161.197,Hyderabad,2025-11-05 22:22:34,Success,Tablet
6,6000007,118362,DEV_84228,103.21.4.221,Mumbai,2026-05-08 22:22:34,Success,Desktop
7,6000008,118815,DEV_61302,103.21.161.0,Kolkata,2025-06-04 22:22:34,Success,Desktop
8,6000009,113309,DEV_12802,103.21.179.30,Kolkata,2025-09-10 22:22:34,Success,Desktop
9,6000010,103526,DEV_92274,103.21.113.250,Hyderabad,2025-03-24 22:22:34,Success,Mobile

In [113]:
clean_device_logins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   login_id        60000 non-null  int64
 1   customer_id     60000 non-null  int64
 2   device_id       60000 non-null  object
 3   ip_address      60000 non-null  object
 4   login_city      60000 non-null  object
 5   login_datetime  60000 non-null  datetime64[ns]
 6   login_status    60000 non-null  object
 7   device_type     60000 non-null  object
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 3.7+ MB

In [114]:
clean_device_logins.describe()

           login_id    customer_id                 login_datetime
count  6.000000e+04   60000.000000                          60000
mean   6.030000e+06  112501.142367  2025-05-25 08:36:22.562683136
min    6.000001e+06  100002.000000            2024-05-22 22:19:06
25%    6.015001e+06  106244.750000     2024-11-20 22:27:53.500000
50%    6.030000e+06  112494.000000            2025-05-23 22:25:43
75%    6.045000e+06  118753.000000  2025-11-26 22:20:27.249999872
max    6.060000e+06  125000.000000            2026-05-26 00:00:00
std    1.732065e+04    7216.678517                            NaN

# Cleaning Chargebacks Table

In [115]:
clean_chargebacks = chargebacks.copy()
clean_chargebacks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   chargeback_id      5000 non-null   int64
 1   transaction_id     5000 non-null   int64
 2   customer_id        4897 non-null   float64
 3   reason_code        5000 non-null   object
 4   chargeback_amount  5000 non-null   float64
 5   reported_date      5000 non-null   object
 6   status             5000 non-null   object
dtypes: float64(2), int64(2), object(3)
memory usage: 273.6+ KB

In [116]:
clean_chargebacks.describe()

       chargeback_id  transaction_id    customer_id  chargeback_amount
count   5.000000e+03    5.000000e+03    4897.000000         5000.00000
mean    9.102500e+06    1.007554e+07  112493.115377         4955.39780
std     1.443520e+03    4.327462e+04    7215.496552         2971.41033
min     9.100001e+06    1.000001e+07  100004.000000         -500.00000
25%     9.101251e+06    1.003863e+07  106397.000000         2399.75000
50%     9.102500e+06    1.007489e+07  112398.000000         4928.00000
75%     9.103750e+06    1.011292e+07  118735.000000         7556.00000
max     9.105000e+06    1.014998e+07  125000.000000        10096.00000

In [117]:
clean_chargebacks.head(10)

,chargeback_id,transaction_id,customer_id,reason_code,chargeback_amount,reported_date,status
0,9100001,10097352,103137.0,Unauthorized,1724.0,2026-03-15,Accepted
1,9100002,10091820,124345.0,Service Not Received,2247.0,2026-04-17,Rejected
2,9100003,10132691,123657.0,Service Not Received,-500.0,2026-03-19,Rejected
3,9100004,10084177,102451.0,Unauthorized,8059.0,2025-11-04,Open
4,9100005,10004645,117281.0,Service Not Received,3257.0,2026-05-16,Open
5,9100006,10090087,106822.0,Service Not Received,3464.0,2026-01-15,Rejected
6,9100007,10082745,109309.0,Unauthorized,4235.0,2025-08-25,Accepted
7,9100008,10004584,123488.0,Unauthorized,504.0,2025-11-29,Open
8,9100009,10130754,106884.0,Service Not Received,139.0,2025-07-11,Open
9,9100010,10131943,124128.0,Unauthorized,3228.0,2026-01-31,Accepted

In [118]:
print(f"Chargebacks before duplicate removal: {len(clean_chargebacks)}")
clean_chargebacks = clean_chargebacks.drop_duplicates()
print(f"Chargebacks after duplicate removal: {len(clean_chargebacks)}")

Chargebacks before duplicate removal: 5000
Chargebacks after duplicate removal: 5000

In [119]:
clean_chargebacks['customer_id'] = clean_chargebacks['customer_id'].fillna(-1).astype(int)

In [120]:
clean_chargebacks['chargeback_amount'] = clean_chargebacks['chargeback_amount'].abs()

In [121]:
clean_chargebacks['reported_date'] = pd.to_datetime(clean_chargebacks['reported_date'])

In [122]:
clean_chargebacks['reason_code'] = clean_chargebacks['reason_code'].str.strip().str.title()
clean_chargebacks['status'] = clean_chargebacks['status'].str.strip().str.title()

In [123]:
clean_chargebacks.head(10)

,chargeback_id,transaction_id,customer_id,reason_code,chargeback_amount,reported_date,status
0,9100001,10097352,103137,Unauthorized,1724.0,2026-03-15,Accepted
1,9100002,10091820,124345,Service Not Received,2247.0,2026-04-17,Rejected
2,9100003,10132691,123657,Service Not Received,500.0,2026-03-19,Rejected
3,9100004,10084177,102451,Unauthorized,8059.0,2025-11-04,Open
4,9100005,10004645,117281,Service Not Received,3257.0,2026-05-16,Open
5,9100006,10090087,106822,Service Not Received,3464.0,2026-01-15,Rejected
6,9100007,10082745,109309,Unauthorized,4235.0,2025-08-25,Accepted
7,9100008,10004584,123488,Unauthorized,504.0,2025-11-29,Open
8,9100009,10130754,106884,Service Not Received,139.0,2025-07-11,Open
9,9100010,10131943,124128,Unauthorized,3228.0,2026-01-31,Accepted

In [124]:
clean_chargebacks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   chargeback_id      5000 non-null   int64
 1   transaction_id     5000 non-null   int64
 2   customer_id        5000 non-null   int64
 3   reason_code        5000 non-null   object
 4   chargeback_amount  5000 non-null   float64
 5   reported_date      5000 non-null   datetime64[ns]
 6   status             5000 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 273.6+ KB

In [125]:
clean_chargebacks.describe()

,chargeback_id,transaction_id,customer_id,chargeback_amount,reported_date
count,5.000000e+03,5.000000e+03,5000.000000,5000.000000,5000
mean,9.102500e+06,1.007554e+07,110175.736600,4976.397800,2025-11-20 03:10:04.800000
min,9.100001e+06,1.000001e+07,-1.000000,101.000000,2025-05-22 00:00:00
25%,9.101251e+06,1.003863e+07,106001.250000,2399.750000,2025-08-20 00:00:00
50%,9.102500e+06,1.007489e+07,112112.000000,4928.000000,2025-11-22 00:00:00
75%,9.103750e+06,1.011292e+07,118550.000000,7556.000000,2026-02-21 06:00:00
max,9.105000e+06,1.014998e+07,125000.000000,10096.000000,2026-05-21 00:00:00
std,1.443520e+03,4.327462e+04,17503.227578,2936.097737,NaN

# Cross-Functional Validation

In [126]:
temporal_check = clean_transactions[['transaction_id', 'account_id', 'transaction_datetime']].merge(
    clean_accounts[['account_id', 'account_open_date']], 
    on='account_id', 
    how='inner'
)

invalid_timeline = temporal_check['transaction_datetime'] < temporal_check['account_open_date']
invalid_txn_ids = temporal_check[invalid_timeline]['transaction_id']

print(f"Found {len(invalid_txn_ids)} ghost transactions occurring before their account existed!")

Found 35846 ghost transactions occurring before their account existed!

In [127]:
clean_customers.to_csv('cleaned_customers.csv', index=False)
clean_transactions.to_csv('cleaned_transactions.csv', index=False)
clean_merchants.to_csv('cleaned_merchants.csv', index=False)
clean_branches.to_csv('cleaned_branches.csv', index=False)
clean_accounts.to_csv('cleaned_accounts.csv', index=False)
clean_credit_cards.to_csv('cleaned_credit_cards.csv', index=False)
clean_atm_logs.to_csv('cleaned_atm_logs.csv', index=False)
clean_fraud_alerts.to_csv('cleaned_fraud_alerts.csv', index=False)
clean_device_logins.to_csv('cleaned_device_logins.csv', index=False)
clean_chargebacks.to_csv('cleaned_chargebacks.csv', index=False)

print("ALL 10 TABLES FULLY CLEANED, VALIDATED, AND EXPORTED SUCCESSFULLY!")

ALL 10 TABLES FULLY CLEANED, VALIDATED, AND EXPORTED SUCCESSFULLY!